import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins} from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const nicoMoji = localFont({
  src: [
    {
      path: "../public/fonts/NicoMoji-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/NicoMoji-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-nico",
  display: "swap",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Doc Cluster",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nicoMoji.variable} antialiased`}
      >
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
